services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - prisma_data:/app/prisma
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({host:'127.0.0.1',port:process.env.PORT||4000,path:'/health'}).on('error',()=>process.exit(1)).on('response',r=>process.exit(r.statusCode===200?0:1)).end()"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: "http://server:4000"
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({host:'127.0.0.1',port:process.env.PORT||3000,path:'/'},res=>process.exit(res.statusCode<500?0:1)).on('error',()=>process.exit(1)).end()"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  prisma_data:
